### ISSUE TITLE
Difficulty Installing

### ISSUE THREAD

**Issue by bradley-varol** [mikeyhalla/MenuTools#1]
Simply running the exec didn't install this for me. I had to create a shortcut and set the `-install` arg.  
I presume this is a bug but an installer would be nice :)

**Comment by xCONFLiCTiONx** [comment]
Thank you for reporting this. I don't have an installer for this for a few reasons.

- I can't really afford to get a license for it to keep windows from complaining about unknown publisher
- I really just made this for myself but made it available for anyone else that would benefit from it

I apologize for any inconveniences and hope that I can find the time to find out why it wouldn't install without having to create a shortcut with -install args. The intention is to just double click the main exe file and the rest falls into place.

**Comment by bradley-varol** [comment]
Thanks for a quick response.  
The MenuTools are amazing, being able to open an elevated cmd from a directory with only two clicks is so useful, hopefully you can work out the installation process. Do many people use the tools?

**Comment by xCONFLiCTiONx** [comment]
To be honest, I have no idea. I stopped working on this project a while back because it does what I want. I am a pc tech and amateur dev so those tools help me a lot and save tons of time and clicks.

I was using another program that had those tools but the dev stopped working on it and the installers were malware infected so I made my own and only because of SharpShell was it even possible for me to do so.

As i stated earlier, if i can find the time to fix the above stated bug, i will, but I am very busy lately.

Please feel free to report any other bugs.

Thank you.

**Comment by xCONFLiCTiONx** [comment]
I have resolved this issue and an installer is now available. Please not that I cannot afford a publishers license so it will get flagged by windows.

Thank you!
