### ISSUE TITLE
How to remove xMenuTools WinExp context menu entries?

### ISSUE THREAD

**Issue by pstein** [mikeyhalla/MenuTools#4]
After having installed and uninstalled xMenuTools the Windows Explorer context menu entries are still alive in Win7 

Very bad.

How can I get rid of them?

I didn't found a menu or checkbox "remove context menus from WinExplorer"

**Comment by xCONFLiCTiONx** [comment]
You have to restart explorer for the entries to be removed. This is why the uninstaller asks if you want to restart explorer upon uninstall. You can also reboot your computer.

Another thing is that the Settings even allows you to remove any and all entries.

This issue will be closed tomorrow unless you are still having issues.

(after this issue is closed only Windows 10 will be supported - Windows 7 is no longer supported by Microsoft and this program is actually only made for Windows 10)

**Comment by xCONFLiCTiONx** [comment]
To make it more clear that you need to restart explorer for the entries to be removed I'll add this to the message on uninstallation. 

I'm closing this issue as resolved...
